### ISSUE TITLE
未考虑AsyncOperation为空的情况

### ISSUE THREAD

**Issue by nantianliao** [ALEXTANGXIAO/GameFramework-Next#10]
UnityGameFramework.Runtime.ResourceComponent中，Update里面（657行），当m_AsyncOperation为空时会报错。

**Comment by Alex-Rachel** [comment]
建议系统了解一下高版本的C#语法，这句代码已经包括了空判断他和空判断是等效的。正常情况是不可能报错的。
![1712416461145](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/45391272/aca48953-6fe8-4f59-8c88-5d1c7b3fb5d4)

**Comment by nantianliao** [comment]
> 建议系统了解一下高版本的C#语法，这句代码已经包括了空判断他和空判断是等效的。正常情况是不可能报错的。 ![1712416461145](https://private-user-images.githubusercontent.com/45391272/320215041-aca48953-6fe8-4f59-8c88-5d1c7b3fb5d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTg1OTAsIm5iZiI6MTcxMjQ1ODI5MCwicGF0aCI6Ii80NTM5MTI3Mi8zMjAyMTUwNDEtYWNhNDg5NTMtNmZlOC00ZjU5LThjODgtNWQxYzdiM2ZiNWQ0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAyNTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjYmQzNDhhODgwNTkxN2MxYzEzMzNjOGI2NTJkNmJlOWMyYzNlNWI1NzU4MGZhOTFmOWU5MzI2OTYwMzZlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.el2KSbJuAYdH5c9qN1VTsf6TmtsSWrdz0sDLJAnrlBA)

了解了，我降版本才会出现的，感谢大佬。
