### ISSUE TITLE
ResourceManager assethandle管理问题

### ISSUE THREAD

**Issue by Wxwind** [ALEXTANGXIAO/GameFramework-Next#14]
yooasset是要自己手动维护释放assethandle的吧，我看好像没有处理handle的释放？是有什么说法吗?

**Comment by Alex-Rachel** [comment]
先多看看源码，assethandle做成对象池来控制释放了。

**Comment by Wxwind** [comment]
> 先多看看源码，assethandle做成对象池来控制释放了。

第一次接触资源管理，看了一下yooasset示例是直接在用到的地方调用assethandle.release；et是挂在场景底下，切换场景时直接卸载资源管理组件；看gf-next没转过弯来想到用对象池方式管理。学到了，感谢
