### ISSUE TITLE
Unity6的调试器面板报错

### ISSUE THREAD

**Issue by XiaoBojun** [ALEXTANGXIAO/GameFramework-Next#17]
![image](https://github.com/user-attachments/assets/e4265f03-59f3-46ce-bb8f-2c6c5d1ede81)
![image](https://github.com/user-attachments/assets/d68db388-47e2-442b-990e-9c13353b95b8)
![image](https://github.com/user-attachments/assets/384b8fb8-e1b2-4640-be8a-b5cf835d5164)
GF和GFN都会在unity6,调试器报错，在目前先禁掉处理

**Comment by XiaoBojun** [comment]
不对，大师，我又悟了，这样改一下就能用了
![image](https://github.com/user-attachments/assets/08c72ea8-92fd-4367-b589-067cbefdae70)
![image](https://github.com/user-attachments/assets/7513f323-e47a-4c06-bc82-8fad332a525f)

**Comment by Alex-Rachel** [comment]
啊 改了啥

**Comment by XiaoBojun** [comment]
private static readonly  TextEditor s_TextEditor=new TextEditor （）;原来是这样写的，unity6不让这么用了，报了上边那些错
