### ISSUE TITLE
报错：卸载场景失败

### ISSUE THREAD

**Issue by whl160118** [ALEXTANGXIAO/GameFramework-Next#6]
启动项目->进入热更代码后加载一个场景，然后退出就会报个错
![image](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/16745827/e37fe5fb-937f-4905-8f2d-fd60ad92ce84)

**Comment by Alex-Rachel** [comment]
已修复

**Comment by whl160118** [comment]
> 已修复

![image](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/16745827/d92f1fda-46ce-4415-ba35-200be23a9230)


好像还是有报错。
