### ISSUE TITLE
> 好像还是有报错

### ISSUE THREAD

**Issue by whl160118** [ALEXTANGXIAO/GameFramework-Next#7]
> 已修复

![image](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/16745827/d92f1fda-46ce-4415-ba35-200be23a9230)

好像还是有报错。

_Originally posted by @whl160118 in https://github.com/ALEXTANGXIAO/GameFramework-Next/issues/6#issuecomment-1963303846_

**Comment by Alex-Rachel** [comment]
提供一下相关代码的截图，我好复现

**Comment by whl160118** [comment]
> 提供一下相关代码的截图，我好复现

我用新工程试了 没问题，先关闭了 我在查查代码
