### ISSUE TITLE
希望能提供一个加载文件夹或文件中的所有资源的接口

### ISSUE THREAD

**Issue by whl160118** [ALEXTANGXIAO/GameFramework-Next#8]
RT：类似Resources.LoadAll

**Comment by Alex-Rachel** [comment]
是有什么需求？yooasset可以通过tag来加载。Assetbundle打包后本身没有原路径的概念。

**Comment by whl160118** [comment]
> 是有什么需求？yooasset可以通过tag来加载。Assetbundle打包后本身没有原路径的概念。

![image](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/16745827/e03fb629-e861-4fec-8856-a4e978a81c06)
这两个方法框架没提供呢，具体需求是：编辑器里做了一个创建某个道具的工具（ScriptableObject），我想把这些道具数据一次性全部加载 然后缓存起来，不用通过道具名称一个个加载了

**Comment by Alex-Rachel** [comment]
首先编辑器的加载建议用AssetDataBbase来做，第二Yooasset不在运行时是无法调用的，第三这个方法的使用场景和效果跟你想的不太一样。

**Comment by whl160118** [comment]
> 首先编辑器的加载建议用AssetDataBbase来做，第二Yooasset不在运行时是无法调用的，第三这个方法的使用场景和效果跟你想的不太一样。

我做的单机游戏，通过编辑器工具栏创建的道具就是游戏里实际用到的数据了，比如道具都存放在AssetRaw/Config下，有没有什么好的方法在启动游戏时加载Config目录下的所有道具，然后把这些道具数据通过id映射关系缓存起来方便后面的使用。

**Comment by Alex-Rachel** [comment]
编辑器下用UnityEditor.AssetDatabase呀。能实现的。非要用yoo的话明天我加一下。或者Config资源组里标记Tag和Userdata

**Comment by whl160118** [comment]
> 编辑器下用UnityEditor.AssetDatabase呀。能实现的。非要用yoo的话明天我加一下。或者Config资源组里标记Tag和Userdata

好的，感谢。

**Comment by Alex-Rachel** [comment]
yoo改接口不是这样用的。是加载资源包内所有资源对象。用UnityEditor.AssetDatabase或者Tag实现。
![image](https://github.com/ALEXTANGXIAO/GameFramework-Next/assets/45391272/c2f641ed-10c9-4604-9d78-81294abcf20b)
https://www.yooasset.com/docs/guide-runtime/CodeTutorial3#%E6%96%B9%E6%B3%95%E5%88%97%E8%A1%A8
