### ISSUE TITLE
希望能有个文档，特别是Luban的使用

### ISSUE THREAD

**Issue by blackspoon434** [ALEXTANGXIAO/GameFramework-Next#9]
感觉和原生Gameframework还是有区别，好不容易把热更的弄清楚了，luban生成的表数据如何在Gameframework调用，又使我无法寸进，希望大大能指导一下

**Comment by whl160118** [comment]
> 感觉和原生Gameframework还是有区别，好不容易把热更的弄清楚了，luban生成的表数据如何在Gameframework调用，又使我无法寸进，希望大大能指导一下

LuBan有文档[（https://luban.doc.code-philosophy.com/）](https://luban.doc.code-philosophy.com/docs/basic)
看教程操作就可以了
